<?php

namespace App\Http\Resources\Auth\Logout;

use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class LogoutSuccusfullyResource extends JsonResource
{
    public function __construct()
    {

    }

    public function withResponse(Request $request, JsonResponse $response)
    {
        parent::withResponse($request, $response->setStatusCode(201)); // TODO: Change the autogenerated stub
    }

    public function toArray(Request $request): array
    {
        return [
            'message' => 'Logged out successfully',
        ];
    }
}
