<?php

namespace App\Http\Resources\Auth\Login;

use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class LoginSuccusfullyResource extends JsonResource
{
    private $token = null;

    public function __construct($token)
    {
        $this->token = $token;
    }

    public function withResponse(Request $request, JsonResponse $response)
    {
        parent::withResponse($request, $response->setStatusCode(201)); // TODO: Change the autogenerated stub
    }

    public function toArray(Request $request): array
    {
        return [
            'token' => $this->token,
        ];
    }
}
