<?php

namespace App\Http\Resources\TimeLog;

use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\ResourceCollection;
use Ramsey\Collection\Collection;

class TimeLogRetrieveRecordCollection extends ResourceCollection
{
    public $collection;

    public function __construct($resource)
    {
        parent::__construct($resource);

        $this->resource = $resource;
    }

    public function withResponse(Request $request, JsonResponse $response)
    {
        parent::withResponse($request, $response->setStatusCode(201)); // TODO: Change the autogenerated stub
    }

    public function toArray(Request $request): array
    {
        return [
            'data' => $this->collection,
        ];
    }
}
