<?php

namespace App\Http\Resources\TimeSheet;

use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class TimeSheetCreatedSuccessResource extends JsonResource
{

    public function __construct()
    {
        
    }

    public function withResponse(Request $request, JsonResponse $response)
    {
        parent::withResponse($request, $response->setStatusCode(201)); // TODO: Change the autogenerated stub
    }

    public function toArray(Request $request): array
    {
        return [
            'message' => 'TimeSheet Created',
        ];
    }
}
